---
language: ruby
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
- jruby-18mode
- jruby-19mode
- rbx-18mode
- rbx-19mode
matrix:
  allow_failures:
  - rvm: 1.8.7
  - rvm: jruby-18mode
  - rvm: rbx-18mode
notifications:
  campfire:
    rooms:
      secure: ! 'cYNdCV3+8DM672sQW27UbHqs2Rrcxv7aXvTZkA7nN0pDKuRWalMVpL2RsRWk

        ZyMqu+m0R7j16Twz70hq5d1Z9+EPayj/vIL7h/HjkNW/hU6G4TARXdSI0YUl

        4C9E5JCL7ZvG/RPUUnecyzYrJGIt+CuHHtONqorgtNQfqOzA8H0='
